// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBamHORq-d6wv3qHzXA4pUfdIcMVxi__yU',
    appId: '1:358669856703:web:230ea56a56fd1c97707b0a',
    messagingSenderId: '358669856703',
    projectId: 'smart-crop-yield',
    authDomain: 'smart-crop-yield.firebaseapp.com',
    storageBucket: 'smart-crop-yield.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1TqT-yx0_yEVgC5ThSHytcuwdik_htA0',
    appId: '1:358669856703:android:209e7c6217a3d33b707b0a',
    messagingSenderId: '358669856703',
    projectId: 'smart-crop-yield',
    storageBucket: 'smart-crop-yield.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_0lJ4Ph0Y93QnsaMwVmy4C3xATb-a8F4',
    appId: '1:358669856703:ios:4e6ea6d8ba324533707b0a',
    messagingSenderId: '358669856703',
    projectId: 'smart-crop-yield',
    storageBucket: 'smart-crop-yield.firebasestorage.app',
    iosBundleId: 'com.example.cropYeild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_0lJ4Ph0Y93QnsaMwVmy4C3xATb-a8F4',
    appId: '1:358669856703:ios:4e6ea6d8ba324533707b0a',
    messagingSenderId: '358669856703',
    projectId: 'smart-crop-yield',
    storageBucket: 'smart-crop-yield.firebasestorage.app',
    iosBundleId: 'com.example.cropYeild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBamHORq-d6wv3qHzXA4pUfdIcMVxi__yU',
    appId: '1:358669856703:web:560835a7791b4ea6707b0a',
    messagingSenderId: '358669856703',
    projectId: 'smart-crop-yield',
    authDomain: 'smart-crop-yield.firebaseapp.com',
    storageBucket: 'smart-crop-yield.firebasestorage.app',
  );
}
